#ifndef C_EXERCISM_H
#define C_EXERCISM_H

#include "c_exercism/hello_world.h"
#include "c_exercism/leap_year.h"
#include "c_exercism/difference_of_squares.h"
#include "c_exercism/grains.h"
#include "c_exercism/resistor_color.h"
#include "c_exercism/collatz_conjecture.h"
#include "c_exercism/queen_attack.h"
#include "c_exercism/darts.h"
#include "c_exercism/resistor_color_duo.h"
#include "c_exercism/hamming.h"
#include "c_exercism/space_age.h"
#include "c_exercism/rna_transcription.h"
#include "c_exercism/binary.h"
#include "c_exercism/eliuds_eggs.h"
#include "c_exercism/two_fer.h"
#include "c_exercism/raindrops.h"
#include "c_exercism/dnd_character.h"
#include "c_exercism/perfect_numbers.h"
#include "c_exercism/high_scores.h"
#include "c_exercism/pangram.h"
#include "c_exercism/resistor_color_trio.h"
#include "c_exercism/armstrong_numbers.h"
#include "c_exercism/isogram.h"
#include "c_exercism/robot_simulator.h"
#include "c_exercism/gigasecond.h"
#include "c_exercism/triangle.h"
#include "c_exercism/luhn.h"
#include "c_exercism/allergies.h"
#include "c_exercism/complex_numbers.h"
#include "c_exercism/sum_of_multiples.h"
#include "c_exercism/nucleotide_count.h"
#include "c_exercism/yacht.h"

#endif